[package]
name = "csv-reader"
version = "0.2.1"
edition = "2021"

[dependencies]
eframe = { version = "0.35.0", default-features = false, features = ["glow", "default_fonts", "x11", "wayland"] }
rfd = "0.17.2"
memmap2 = "0.9"
memchr = "2"
rayon = "1"

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
strip = true

[package.metadata.packager]
product-name = "CSV Reader"
identifier = "top.fulracoco.csvreader"
icons = ["icons/32x32.png", "icons/128x128.png", "icons/icon.icns", "icons/icon.ico"]
